import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, GradientButton, Icon, SecondaryButton } from "@/components/taskflow";
import { Category, createCategory, deleteCategory, getApiErrorMessage, listCategories, updateCategory } from "@/lib/taskflow-auth";
import { TaskFlowTheme as T } from "@/constants/theme";

const colors = ["#9A6BFF", "#4B8DFF", "#F4A340", "#3DDB82", "#4BC0C8", "#EA668F"];
export default function CategoriesScreen() {
  const [items, setItems] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<Category | null>(null); const [modalOpen, setModalOpen] = useState(false); const [name, setName] = useState(""); const [color, setColor] = useState(colors[0]); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setItems(await listCategories()); } catch (err) { setError(getApiErrorMessage(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  function openEditor(category?: Category) { setEditing(category ?? null); setModalOpen(true); setName(category?.name ?? ""); setColor(category?.color ?? colors[0]); }
  async function save() { if (!name.trim()) return; setSaving(true); try { if (editing) await updateCategory(editing.id, { name: name.trim(), color, icon: editing.icon }); else await createCategory({ name: name.trim(), color, icon: "folder-outline" }); setEditing(null); setModalOpen(false); setName(""); await load(); } catch (err) { setError(getApiErrorMessage(err)); } finally { setSaving(false); } }
  function remove(category: Category) { Alert.alert("Delete category?", `Tasks will keep their current category text.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { await deleteCategory(category.id); await load(); } catch (err) { setError(getApiErrorMessage(err)); } } }]); }
  return <ScreenContainer edges={["top", "left", "right"]} style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Icon name="arrow-back" color={T.colors.text} /></Pressable><View><Text style={styles.eyebrow}>ORGANIZE YOUR WORK</Text><Text style={styles.title}>Categories</Text></View><Pressable onPress={() => openEditor()} style={styles.add}><Icon name="add" color={T.colors.text} size={22} /></Pressable></View><Text style={styles.subtitle}>Group your tasks by focus, project, or energy.</Text>{error && <Text style={styles.error}>{error}</Text>}{loading ? <ActivityIndicator color={T.colors.primaryGlow} /> : <View style={styles.list}>{items.map((category) => <Card key={category.id} style={styles.categoryCard}><View style={[styles.categoryIcon, { backgroundColor: `${category.color}24` }]}><Icon name="folder-outline" color={category.color} size={20} /></View><View style={styles.copy}><Text style={styles.categoryName}>{category.name}</Text><Text style={styles.count}>{category.taskCount} {category.taskCount === 1 ? "task" : "tasks"}</Text></View><Pressable onPress={() => openEditor(category)} style={styles.smallButton}><Icon name="create-outline" color={T.colors.secondary} size={18} /></Pressable><Pressable onPress={() => remove(category)} style={styles.smallButton}><Icon name="trash-outline" color={T.colors.warning} size={18} /></Pressable></Card>)}</View>}{!loading && <GradientButton label="Create category" icon="add" onPress={() => openEditor()} />}</ScrollView><Modal visible={modalOpen} transparent animationType="slide" onRequestClose={() => setEditing(null)}><View style={styles.modalBackdrop}><View style={styles.modal}><Text style={styles.modalTitle}>{editing ? "Edit category" : "New category"}</Text><TextInput value={name} onChangeText={setName} placeholder="Category name" placeholderTextColor={T.colors.muted} style={styles.input} autoFocus /><Text style={styles.label}>Color</Text><View style={styles.colorRow}>{colors.map((value) => <Pressable key={value} onPress={() => setColor(value)} style={[styles.colorChoice, { backgroundColor: value }, color === value && styles.selectedColor]} />)}</View><GradientButton label={saving ? "Saving…" : editing ? "Save changes" : "Create category"} onPress={() => void save()} disabled={saving || !name.trim()} /><SecondaryButton label="Cancel" onPress={() => { setEditing(null); setModalOpen(false); setName(""); }} /></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ container: { backgroundColor: T.colors.midnight }, content: { padding: 20, paddingBottom: 45, gap: 16 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 38, height: 38, borderRadius: 19, backgroundColor: T.colors.navySurface, alignItems: "center", justifyContent: "center" }, eyebrow: { color: T.colors.primaryGlow, fontSize: 9, letterSpacing: 1.4, fontWeight: "700" }, title: { color: T.colors.text, fontSize: 25, fontWeight: "800", marginTop: 4 }, add: { marginLeft: "auto", width: 38, height: 38, borderRadius: 19, backgroundColor: T.colors.primary, alignItems: "center", justifyContent: "center" }, subtitle: { color: T.colors.muted, fontSize: 13, lineHeight: 19 }, list: { gap: 10 }, categoryCard: { flexDirection: "row", alignItems: "center", padding: 13 }, categoryIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, marginLeft: 12 }, categoryName: { color: T.colors.text, fontWeight: "700", fontSize: 14 }, count: { color: T.colors.muted, fontSize: 11, marginTop: 4 }, smallButton: { padding: 8 }, error: { color: T.colors.warning, fontSize: 12 }, modalBackdrop: { flex: 1, backgroundColor: "#000000AA", justifyContent: "flex-end" }, modal: { backgroundColor: T.colors.navySurface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, gap: 16, borderWidth: 1, borderColor: T.colors.border }, modalTitle: { color: T.colors.text, fontSize: 18, fontWeight: "800" }, input: { minHeight: 48, borderRadius: 13, backgroundColor: T.colors.raisedSurface, borderWidth: 1, borderColor: T.colors.border, color: T.colors.text, paddingHorizontal: 14 }, label: { color: T.colors.text, fontWeight: "700", fontSize: 12 }, colorRow: { flexDirection: "row", gap: 12 }, colorChoice: { width: 30, height: 30, borderRadius: 15 }, selectedColor: { borderWidth: 3, borderColor: T.colors.text }, });
