import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const metrics = [['All Tasks', '24', 'purple'], ['Completed', '16', 'green'], ['In Progress', '5', 'blue'], ['Pending', '3', 'orange']];
function App() {
  return <div className="shell"><aside className="sidebar"><div className="brand">Task<span>Flow</span></div><div className="admin-label">ADMIN CONSOLE</div>{['Overview', 'Tasks', 'Calendar', 'Analytics', 'Categories', 'Settings'].map((item, index) => <button className={`side-item ${index === 0 ? 'active' : ''}`} key={item}><span>{['⌂', '☷', '□', '▥', '◈', '⚙'][index]}</span>{item}</button>)}</aside><main className="main"><header className="topbar"><div><p className="eyebrow">WORKSPACE OVERVIEW</p><h1>Good morning, Ermiya</h1><p className="muted">Here’s what’s happening with your tasks today.</p></div><button className="profile">E</button></header><section className="metrics">{metrics.map(([label, value, tone]) => <div className={`metric-card ${tone}`} key={label}><span>{label}</span><strong>{value}</strong><small>Updated just now</small></div>)}</section><section className="grid"><div className="panel wide"><div className="panel-head"><div><h2>Productivity trend</h2><p className="muted">Completed tasks over the last 7 days</p></div><button className="select">This week ˅</button></div><div className="chart"><div className="chart-line"><i style={{ height: '35%' }} /><i style={{ height: '50%' }} /><i style={{ height: '42%' }} /><i style={{ height: '72%' }} /><i style={{ height: '58%' }} /><i style={{ height: '84%' }} /><i style={{ height: '92%' }} /></div><div className="axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div><div className="panel"><div className="panel-head"><h2>Task status</h2><span className="muted">This week</span></div><div className="status-list"><div><span className="dot green-dot" />Completed <b>16</b></div><div><span className="dot blue-dot" />In progress <b>5</b></div><div><span className="dot orange-dot" />Pending <b>3</b></div></div></div></section></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
