import { StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { Card, FilterTabs, ScreenHeader } from '@/components/taskflow';
import { TaskFlowTheme as T } from '@/constants/theme';

export default function AnalyticsScreen() {
  return <ScreenContainer className="px-4 pt-3"><View style={styles.page}><ScreenHeader title="Analytics" leftIcon="menu-outline" rightIcon="calendar-outline" /><FilterTabs tabs={['Week', 'Month', 'Year', 'Custom']} active="Month" /><Text style={styles.section}>Overview</Text><View style={styles.kpis}><Card style={styles.kpi}><Text style={styles.kpiLabel}>Tasks Completed</Text><Text style={styles.kpiValue}>72</Text><Text style={styles.kpiDelta}>+18% vs last month</Text></Card><Card style={styles.kpi}><Text style={styles.kpiLabel}>Total Focus Time</Text><Text style={styles.kpiValue}>42h 15m</Text><Text style={styles.kpiDelta}>+12% vs last month</Text></Card></View><Card style={styles.chart}><View style={styles.chartHeader}><Text style={styles.section}>Productivity Trend</Text><Text style={styles.kpiLabel}>This Month ˅</Text></View><View style={styles.chartArea}>{[30, 46, 38, 68, 55, 82, 92].map((height, index) => <View key={index} style={styles.barGroup}><View style={[styles.bar, { height }]} /><Text style={styles.axis}>{['Apr 28', 'May 4', 'May 11', 'May 18', 'May 25', '', ''][index]}</Text></View>)}</View></Card></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, section: { color: T.colors.text, fontSize: 15, fontWeight: '700', marginTop: 20, marginBottom: 11 }, kpis: { flexDirection: 'row', gap: 9 }, kpi: { flex: 1, padding: 13 }, kpiLabel: { color: T.colors.muted, fontSize: 10 }, kpiValue: { color: T.colors.text, fontSize: 20, fontWeight: '800', marginTop: 8 }, kpiDelta: { color: T.colors.success, fontSize: 9, marginTop: 5 }, chart: { marginTop: 12, padding: 14 }, chartHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, chartArea: { height: 150, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', paddingTop: 18 }, barGroup: { alignItems: 'center', gap: 8 }, bar: { width: 18, backgroundColor: T.colors.primary, borderTopLeftRadius: 7, borderTopRightRadius: 7 }, axis: { color: T.colors.muted, fontSize: 8 } });
