import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, EmptyState, FloatingActionButton, Icon, TaskCard } from "@/components/taskflow";
import { Task, getApiErrorMessage, getCalendarTasks } from "@/lib/taskflow-auth";
import { TaskFlowTheme as T } from "@/constants/theme";

function isoDate(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function monthLabel(date: Date) { return date.toLocaleDateString(undefined, { month: "long", year: "numeric" }); }
function buildCalendarDays(month: Date) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }

export default function CalendarScreen() {
  const [month, setMonth] = useState(() => new Date()); const [selected, setSelected] = useState(() => new Date()); const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const days = useMemo(() => buildCalendarDays(month), [month]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await getCalendarTasks(isoDate(selected)); setTasks(result.items); } catch (err) { setError(getApiErrorMessage(err)); } finally { setLoading(false); } }, [selected]);
  useEffect(() => { void load(); }, [load]);
  const today = isoDate(new Date());
  return <ScreenContainer edges={["top", "left", "right"]} style={styles.container}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>PLAN YOUR TIME</Text><Text style={styles.title}>Calendar</Text></View><Pressable onPress={() => router.push("/search" as any)} style={styles.iconButton}><Icon name="search-outline" color={T.colors.text} size={21} /></Pressable></View>
    <Card style={styles.calendarCard}><View style={styles.monthRow}><Pressable onPress={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() - 1, 1))} style={styles.monthButton}><Icon name="chevron-back" color={T.colors.text} /></Pressable><Text style={styles.monthTitle}>{monthLabel(month)}</Text><Pressable onPress={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() + 1, 1))} style={styles.monthButton}><Icon name="chevron-forward" color={T.colors.text} /></Pressable></View><View style={styles.weekRow}>{["S", "M", "T", "W", "T", "F", "S"].map((day, index) => <Text key={`${day}-${index}`} style={styles.weekText}>{day}</Text>)}</View><View style={styles.grid}>{days.map((date) => { const current = isoDate(date); const active = current === isoDate(selected); const muted = date.getMonth() !== month.getMonth(); return <Pressable key={current} onPress={() => { setSelected(date); setMonth(new Date(date.getFullYear(), date.getMonth(), 1)); }} style={[styles.day, active && styles.activeDay]}><Text style={[styles.dayText, muted && styles.mutedDayText, active && styles.activeDayText]}>{date.getDate()}</Text>{current === today && <View style={styles.todayDot} />}</Pressable>; })}</View></Card>
    <View style={styles.sectionHeader}><View><Text style={styles.sectionTitle}>{selected.toLocaleDateString(undefined, { weekday: "long" })}</Text><Text style={styles.sectionSubtitle}>{selected.toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}</Text></View><Text style={styles.taskCount}>{tasks.length} {tasks.length === 1 ? "task" : "tasks"}</Text></View>
    {loading ? <View style={styles.loading}><ActivityIndicator color={T.colors.primaryGlow} /><Text style={styles.muted}>Loading tasks for this date…</Text></View> : error ? <Card><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Try again</Text></Pressable></Card> : tasks.length === 0 ? <EmptyState title="Nothing scheduled" message="Add a task with this due date to see it here." action={<Pressable onPress={() => router.push("/task/form")} style={styles.inlineAction}><Text style={styles.inlineActionText}>Add task</Text></Pressable>} /> : <View style={styles.taskList}>{tasks.map((task) => <TaskCard key={task.id} title={task.title} status={task.status} time={task.time || "Any time"} category={task.category || "Other"} onPress={() => router.push(`/task/${task.id}`)} />)}</View>}
  </ScrollView><FloatingActionButton onPress={() => router.push("/task/form")} /></ScreenContainer>;
}

const styles = StyleSheet.create({ container: { backgroundColor: T.colors.midnight }, content: { padding: 20, paddingBottom: 110, gap: 18 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: T.colors.primaryGlow, fontSize: 10, letterSpacing: 1.6, fontWeight: "700" }, title: { color: T.colors.text, fontSize: 27, fontWeight: "800", marginTop: 5 }, iconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: T.colors.navySurface, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: T.colors.border }, calendarCard: { padding: 14, gap: 14 }, monthRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, monthTitle: { color: T.colors.text, fontSize: 16, fontWeight: "800" }, monthButton: { padding: 8 }, weekRow: { flexDirection: "row", justifyContent: "space-around" }, weekText: { color: T.colors.muted, fontSize: 11, fontWeight: "700", width: 35, textAlign: "center" }, grid: { flexDirection: "row", flexWrap: "wrap" }, day: { width: `${100 / 7}%`, height: 42, alignItems: "center", justifyContent: "center", position: "relative" }, activeDay: { backgroundColor: T.colors.primary, borderRadius: 14 }, dayText: { color: T.colors.text, fontSize: 13, fontWeight: "600" }, activeDayText: { fontWeight: "800" }, mutedDayText: { color: T.colors.muted, opacity: 0.45 }, todayDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: T.colors.secondary, position: "absolute", bottom: 4 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, sectionTitle: { color: T.colors.text, fontSize: 18, fontWeight: "800" }, sectionSubtitle: { color: T.colors.muted, fontSize: 12, marginTop: 3 }, taskCount: { color: T.colors.primaryGlow, fontWeight: "700", fontSize: 12 }, taskList: { gap: 10 }, loading: { alignItems: "center", gap: 10, paddingVertical: 35 }, muted: { color: T.colors.muted, fontSize: 12 }, error: { color: T.colors.warning, fontSize: 13, lineHeight: 19 }, retry: { color: T.colors.primaryGlow, fontWeight: "700", marginTop: 12 }, inlineAction: { marginTop: 10, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, backgroundColor: T.colors.primary }, inlineActionText: { color: T.colors.text, fontWeight: "700" }, });
