import { StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { Card, Icon, ScreenHeader } from '@/components/taskflow';
import { TaskFlowTheme as T } from '@/constants/theme';

const rows = [['color-palette-outline', 'Appearance', 'Dark'], ['notifications-outline', 'Notifications', ''], ['timer-outline', 'Focus Mode', ''], ['list-outline', 'Default View', 'List'], ['language-outline', 'Language', 'English'], ['cloud-outline', 'Backup & Sync', ''], ['shield-checkmark-outline', 'Privacy & Security', ''], ['information-circle-outline', 'About TaskFlow', 'v1.0.0']] as const;
export default function ProfileScreen() {
  return <ScreenContainer className="px-4 pt-3"><View style={styles.page}><ScreenHeader title="Settings" leftIcon="menu-outline" rightIcon="settings-outline" /><Card style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>E</Text></View><View><Text style={styles.name}>Ermiya</Text><Text style={styles.email}>Productivity workspace</Text></View></Card><View style={styles.list}>{rows.map(([icon, label, detail]) => <View key={label} style={styles.row}><Icon name={icon as any} size={18} color={T.colors.muted} /><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowDetail}>{detail}</Text><Icon name="chevron-forward" size={16} color={T.colors.muted} /></View>)}</View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, profile: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 15 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: T.colors.primary, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: T.colors.text, fontSize: 20, fontWeight: '800' }, name: { color: T.colors.text, fontSize: 15, fontWeight: '700' }, email: { color: T.colors.muted, fontSize: 11, marginTop: 4 }, list: { backgroundColor: T.colors.navySurface, borderRadius: T.radius.lg, borderWidth: 1, borderColor: T.colors.border, paddingHorizontal: 14 }, row: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: T.colors.divider }, rowLabel: { color: T.colors.text, fontSize: 12, flex: 1 }, rowDetail: { color: T.colors.muted, fontSize: 11 } });
