import { StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { Card, FloatingActionButton, ScreenHeader } from '@/components/taskflow';
import { TaskFlowTheme as T } from '@/constants/theme';

export default function CalendarScreen() {
  const days = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];
  return <ScreenContainer className="px-4 pt-3"><View style={styles.page}><ScreenHeader title="Calendar" leftIcon="arrow-back" rightIcon="settings-outline" /><Text style={styles.month}>May 2025 <Text style={styles.chevron}>‹   ›</Text></Text><Card style={styles.calendar}><View style={styles.week}>{days.map((day, index) => <Text key={`${day}-${index}`} style={styles.weekday}>{day}</Text>)}</View><View style={styles.grid}>{Array.from({ length: 35 }, (_, index) => { const value = index - 3; const selected = value === 20; return <View key={index} style={[styles.day, selected && styles.selected]}><Text style={[styles.dayText, selected && styles.selectedText]}>{value > 0 && value <= 31 ? value : ''}</Text></View>; })}</View></Card><Text style={styles.agendaTitle}>Tuesday, May 20</Text><Card style={styles.agenda}><View style={[styles.agendaRail, { backgroundColor: T.colors.primary }]} /><View style={styles.agendaCopy}><Text style={styles.taskName}>Design new landing page</Text><Text style={styles.taskMeta}>10:00 AM — 12:30 PM  ·  Work</Text></View><Text style={styles.agendaTime}>10:00 AM</Text></Card><Card style={styles.agenda}><View style={[styles.agendaRail, { backgroundColor: T.colors.secondary }]} /><View style={styles.agendaCopy}><Text style={styles.taskName}>Team stand-up meeting</Text><Text style={styles.taskMeta}>01:00 — 01:30 PM  ·  Work</Text></View><Text style={styles.agendaTime}>01:30 PM</Text></Card><View style={styles.fab}><FloatingActionButton /></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, month: { color: T.colors.text, fontSize: 16, fontWeight: '700', marginBottom: 12 }, chevron: { color: T.colors.muted, fontSize: 20, fontWeight: '400' }, calendar: { padding: 13, marginBottom: 22 }, week: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12 }, weekday: { color: T.colors.muted, fontSize: 10, width: 30, textAlign: 'center' }, grid: { flexDirection: 'row', flexWrap: 'wrap' }, day: { width: '14.28%', height: 36, alignItems: 'center', justifyContent: 'center' }, selected: { backgroundColor: T.colors.primary, borderRadius: 18 }, dayText: { color: T.colors.text, fontSize: 11 }, selectedText: { fontWeight: '800' }, agendaTitle: { color: T.colors.text, fontSize: 13, fontWeight: '700', marginBottom: 10 }, agenda: { padding: 11, flexDirection: 'row', alignItems: 'center', marginBottom: 8 }, agendaRail: { width: 3, height: 42, borderRadius: 2, marginRight: 11 }, agendaCopy: { flex: 1, gap: 4 }, taskName: { color: T.colors.text, fontSize: 12, fontWeight: '600' }, taskMeta: { color: T.colors.muted, fontSize: 10 }, agendaTime: { color: T.colors.muted, fontSize: 9 }, fab: { position: 'absolute', right: 0, bottom: 18 } });
